feat: create license
Leukocyte-Lab/AGH2-Installer pull request #17
Opened 2022-06-01 05:51 UTC by ray31245

generate secret and create license

2022-06-01 08:19 UTC, Aries0d0f requested changes

2022-06-01 08:19 UTC, Aries0d0f commented on scripts/gen/create_license.sh
> +  -H 'Authorization: Bearer admin-9dcbc0067b57d179f2ae3a64f6f11d06342294fd72c3d46e59a141d53e03f4edv3' \
**DO NOT** leave token on committed files, removed this and please do force-push.

2022-06-29 06:09 UTC, knowlet approved these changes

2022-06-29 06:10 UTC, Aries0d0f approved these changes

2022-06-29 06:10 UTC, merged